load("//bzl:module.bzl", "isaac_cc_module")

isaac_cc_module(
    name = "pololu",
    visibility = ["//visibility:public"],
    deps = [
        "//packages/pololu/components:pololu_driver",
    ]
)

